version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: quarkusdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quarkus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quarkus-microservice
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: admin
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkusdb
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quarkus-network

volumes:
  postgres_data:

networks:
  quarkus-network:
    driver: bridge
