name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache dependencias Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        

      
    - name: Compilar aplicación
      working-directory: ./Quarkus-Docker
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
      
    - name: Construir imagen Docker
      working-directory: ./Quarkus-Docker
      run: |
        docker build -t quarkus-microservice:${{ github.sha }} .
        docker tag quarkus-microservice:${{ github.sha }} quarkus-microservice:latest
        

